server {
    # On écoute uniquement sur le port 443 avec SSL (exigence absolue du sujet)
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name tcarlier.42.fr;

    # Les chemins vers les certificats SSL (que l'on va générer dans le Dockerfile)
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Les protocoles sécurisés autorisés (TLSv1.2 ou TLSv1.3 obligatoires selon le sujet)
    ssl_protocols TLSv1.2 TLSv1.3;

    # Le dossier où NGINX doit aller chercher les fichiers de WordPress
    root /var/www/html;
    index index.php index.html index.htm;

    # On redirige les requêtes vers le bon fichier
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # C'est ici la magie : on dit à NGINX d'envoyer tout le PHP au conteneur WordPress
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # On pointe vers notre conteneur "wordpress" sur le port "9000"
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}